export const GroupSeed = [
  {
    name: "Antenna1",
    groupId: 1,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Antenna2",
    groupId: 2,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Antenna3",
    groupId: 3,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Antenna4",
    groupId: 4,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Antenna5",
    groupId: 5,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Table1",
    groupId: 6,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Table2",
    groupId: 7,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair1",
    groupId: 8,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair2",
    groupId: 9,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair3",
    groupId: 10,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair4",
    groupId: 11,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair5",
    groupId: 12,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair6",
    groupId: 13,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair7",
    groupId: 14,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Chair8",
    groupId: 15,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Slipper1",
    groupId: 16,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Slipper2",
    groupId: 17,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Slipper3",
    groupId: 18,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Slipper4",
    groupId: 19,
    filterId: 0,
    existingNum: 2,
    description: "",
  },
  {
    name: "Clothes1",
    groupId: 20,
    filterId: 0,
    existingNum: 4,
    description: "",
  },
  {
    name: "Clothes2",
    groupId: 21,
    filterId: 0,
    existingNum: 4,
    description: "",
  },
  {
    name: "Stick1",
    groupId: 22,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
  {
    name: "Stick2",
    groupId: 23,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
  {
    name: "Wheelchair1",
    groupId: 24,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
  {
    name: "Wheelchair2",
    groupId: 25,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
  {
    name: "NameTag1",
    groupId: 26,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
  {
    name: "NameTag2",
    groupId: 27,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
  {
    name: "NameTag3",
    groupId: 28,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
  {
    name: "NameTag4",
    groupId: 29,
    filterId: 0,
    existingNum: 1,
    description: "",
  },
];